spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/phone_shop_db
    username: postgres
    password: 123079
  jpa:
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: salinchhun123079@gmail.com
    password: atmd nzxr vqqs qxwq
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days
server:
  error:
    include-message: always

#logging:
#  level:
##    springframework:
##    security: DEBUG
#    org.hibernate: info
#    org.hibernate.SQL: debug
#    org.hibernate.orm.jdbc.bind: trace

